/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PruebaRouteImport } from './routes/prueba'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MenuRouteRouteImport } from './routes/_menu/route'
import { Route as CajaIndexRouteImport } from './routes/caja/index'
import { Route as MenuIndexRouteImport } from './routes/_menu/index'
import { Route as InventarioInvRouteImport } from './routes/inventario/_inv'
import { Route as InventarioInvIndexRouteImport } from './routes/inventario/_inv.index'
import { Route as MenuEmpleadosIndexRouteImport } from './routes/_menu/empleados/index'
import { Route as MenuHistorialVentasRouteImport } from './routes/_menu/historial.ventas'
import { Route as MenuHistorialComprasRouteImport } from './routes/_menu/historial.compras'
import { Route as MenuEmpleadosCrearRouteImport } from './routes/_menu/empleados/crear'
import { Route as MenuEmpleadosIDRouteImport } from './routes/_menu/empleados/$ID'
import { Route as InventarioInvProveedoresIndexRouteImport } from './routes/inventario/_inv.proveedores/index'
import { Route as InventarioInvProductosIndexRouteImport } from './routes/inventario/_inv.productos/index'
import { Route as InventarioInvProveedoresCrearRouteImport } from './routes/inventario/_inv.proveedores/crear'
import { Route as InventarioInvProductosCrearRouteImport } from './routes/inventario/_inv.productos/crear'
import { Route as InventarioInvPaquetesCrearRouteImport } from './routes/inventario/_inv.paquetes/crear'
import { Route as MenuEmpleadosEditarIDRouteImport } from './routes/_menu/empleados/editar.$ID'
import { Route as InventarioInvProveedoresEditarIDRouteImport } from './routes/inventario/_inv.proveedores/editar.$ID'
import { Route as InventarioInvProductosEditarIDRouteImport } from './routes/inventario/_inv.productos/editar.$ID'
import { Route as InventarioInvPaquetesEditarIDRouteImport } from './routes/inventario/_inv.paquetes/editar.$ID'

const PruebaRoute = PruebaRouteImport.update({
  id: '/prueba',
  path: '/prueba',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRouteRoute = MenuRouteRouteImport.update({
  id: '/_menu',
  getParentRoute: () => rootRouteImport,
} as any)
const CajaIndexRoute = CajaIndexRouteImport.update({
  id: '/caja/',
  path: '/caja/',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuIndexRoute = MenuIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MenuRouteRoute,
} as any)
const InventarioInvRoute = InventarioInvRouteImport.update({
  id: '/_inv',
  getParentRoute: () => InventarioRoute,
} as any)
const InventarioInvIndexRoute = InventarioInvIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventarioInvRoute,
} as any)
const MenuEmpleadosIndexRoute = MenuEmpleadosIndexRouteImport.update({
  id: '/empleados/',
  path: '/empleados/',
  getParentRoute: () => MenuRouteRoute,
} as any)
const MenuHistorialVentasRoute = MenuHistorialVentasRouteImport.update({
  id: '/historial/ventas',
  path: '/historial/ventas',
  getParentRoute: () => MenuRouteRoute,
} as any)
const MenuHistorialComprasRoute = MenuHistorialComprasRouteImport.update({
  id: '/historial/compras',
  path: '/historial/compras',
  getParentRoute: () => MenuRouteRoute,
} as any)
const MenuEmpleadosCrearRoute = MenuEmpleadosCrearRouteImport.update({
  id: '/empleados/crear',
  path: '/empleados/crear',
  getParentRoute: () => MenuRouteRoute,
} as any)
const MenuEmpleadosIDRoute = MenuEmpleadosIDRouteImport.update({
  id: '/empleados/$ID',
  path: '/empleados/$ID',
  getParentRoute: () => MenuRouteRoute,
} as any)
const InventarioInvProveedoresIndexRoute =
  InventarioInvProveedoresIndexRouteImport.update({
    id: '/proveedores/',
    path: '/proveedores/',
    getParentRoute: () => InventarioInvRoute,
  } as any)
const InventarioInvProductosIndexRoute =
  InventarioInvProductosIndexRouteImport.update({
    id: '/productos/',
    path: '/productos/',
    getParentRoute: () => InventarioInvRoute,
  } as any)
const InventarioInvProveedoresCrearRoute =
  InventarioInvProveedoresCrearRouteImport.update({
    id: '/proveedores/crear',
    path: '/proveedores/crear',
    getParentRoute: () => InventarioInvRoute,
  } as any)
const InventarioInvProductosCrearRoute =
  InventarioInvProductosCrearRouteImport.update({
    id: '/productos/crear',
    path: '/productos/crear',
    getParentRoute: () => InventarioInvRoute,
  } as any)
const InventarioInvPaquetesCrearRoute =
  InventarioInvPaquetesCrearRouteImport.update({
    id: '/paquetes/crear',
    path: '/paquetes/crear',
    getParentRoute: () => InventarioInvRoute,
  } as any)
const MenuEmpleadosEditarIDRoute = MenuEmpleadosEditarIDRouteImport.update({
  id: '/empleados/editar/$ID',
  path: '/empleados/editar/$ID',
  getParentRoute: () => MenuRouteRoute,
} as any)
const InventarioInvProveedoresEditarIDRoute =
  InventarioInvProveedoresEditarIDRouteImport.update({
    id: '/proveedores/editar/$ID',
    path: '/proveedores/editar/$ID',
    getParentRoute: () => InventarioInvRoute,
  } as any)
const InventarioInvProductosEditarIDRoute =
  InventarioInvProductosEditarIDRouteImport.update({
    id: '/productos/editar/$ID',
    path: '/productos/editar/$ID',
    getParentRoute: () => InventarioInvRoute,
  } as any)
const InventarioInvPaquetesEditarIDRoute =
  InventarioInvPaquetesEditarIDRouteImport.update({
    id: '/paquetes/editar/$ID',
    path: '/paquetes/editar/$ID',
    getParentRoute: () => InventarioInvRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/prueba': typeof PruebaRoute
  '/inventario': typeof InventarioInvRouteWithChildren
  '/': typeof MenuIndexRoute
  '/caja': typeof CajaIndexRoute
  '/empleados/$ID': typeof MenuEmpleadosIDRoute
  '/empleados/crear': typeof MenuEmpleadosCrearRoute
  '/historial/compras': typeof MenuHistorialComprasRoute
  '/historial/ventas': typeof MenuHistorialVentasRoute
  '/empleados': typeof MenuEmpleadosIndexRoute
  '/inventario/': typeof InventarioInvIndexRoute
  '/empleados/editar/$ID': typeof MenuEmpleadosEditarIDRoute
  '/inventario/paquetes/crear': typeof InventarioInvPaquetesCrearRoute
  '/inventario/productos/crear': typeof InventarioInvProductosCrearRoute
  '/inventario/proveedores/crear': typeof InventarioInvProveedoresCrearRoute
  '/inventario/productos': typeof InventarioInvProductosIndexRoute
  '/inventario/proveedores': typeof InventarioInvProveedoresIndexRoute
  '/inventario/paquetes/editar/$ID': typeof InventarioInvPaquetesEditarIDRoute
  '/inventario/productos/editar/$ID': typeof InventarioInvProductosEditarIDRoute
  '/inventario/proveedores/editar/$ID': typeof InventarioInvProveedoresEditarIDRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/prueba': typeof PruebaRoute
  '/': typeof MenuIndexRoute
  '/caja': typeof CajaIndexRoute
  '/empleados/$ID': typeof MenuEmpleadosIDRoute
  '/empleados/crear': typeof MenuEmpleadosCrearRoute
  '/historial/compras': typeof MenuHistorialComprasRoute
  '/historial/ventas': typeof MenuHistorialVentasRoute
  '/empleados': typeof MenuEmpleadosIndexRoute
  '/inventario': typeof InventarioInvIndexRoute
  '/empleados/editar/$ID': typeof MenuEmpleadosEditarIDRoute
  '/inventario/paquetes/crear': typeof InventarioInvPaquetesCrearRoute
  '/inventario/productos/crear': typeof InventarioInvProductosCrearRoute
  '/inventario/proveedores/crear': typeof InventarioInvProveedoresCrearRoute
  '/inventario/productos': typeof InventarioInvProductosIndexRoute
  '/inventario/proveedores': typeof InventarioInvProveedoresIndexRoute
  '/inventario/paquetes/editar/$ID': typeof InventarioInvPaquetesEditarIDRoute
  '/inventario/productos/editar/$ID': typeof InventarioInvProductosEditarIDRoute
  '/inventario/proveedores/editar/$ID': typeof InventarioInvProveedoresEditarIDRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_menu': typeof MenuRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/prueba': typeof PruebaRoute
  '/inventario/_inv': typeof InventarioInvRouteWithChildren
  '/_menu/': typeof MenuIndexRoute
  '/caja/': typeof CajaIndexRoute
  '/_menu/empleados/$ID': typeof MenuEmpleadosIDRoute
  '/_menu/empleados/crear': typeof MenuEmpleadosCrearRoute
  '/_menu/historial/compras': typeof MenuHistorialComprasRoute
  '/_menu/historial/ventas': typeof MenuHistorialVentasRoute
  '/_menu/empleados/': typeof MenuEmpleadosIndexRoute
  '/inventario/_inv/': typeof InventarioInvIndexRoute
  '/_menu/empleados/editar/$ID': typeof MenuEmpleadosEditarIDRoute
  '/inventario/_inv/paquetes/crear': typeof InventarioInvPaquetesCrearRoute
  '/inventario/_inv/productos/crear': typeof InventarioInvProductosCrearRoute
  '/inventario/_inv/proveedores/crear': typeof InventarioInvProveedoresCrearRoute
  '/inventario/_inv/productos/': typeof InventarioInvProductosIndexRoute
  '/inventario/_inv/proveedores/': typeof InventarioInvProveedoresIndexRoute
  '/inventario/_inv/paquetes/editar/$ID': typeof InventarioInvPaquetesEditarIDRoute
  '/inventario/_inv/productos/editar/$ID': typeof InventarioInvProductosEditarIDRoute
  '/inventario/_inv/proveedores/editar/$ID': typeof InventarioInvProveedoresEditarIDRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/prueba'
    | '/inventario'
    | '/'
    | '/caja'
    | '/empleados/$ID'
    | '/empleados/crear'
    | '/historial/compras'
    | '/historial/ventas'
    | '/empleados'
    | '/inventario/'
    | '/empleados/editar/$ID'
    | '/inventario/paquetes/crear'
    | '/inventario/productos/crear'
    | '/inventario/proveedores/crear'
    | '/inventario/productos'
    | '/inventario/proveedores'
    | '/inventario/paquetes/editar/$ID'
    | '/inventario/productos/editar/$ID'
    | '/inventario/proveedores/editar/$ID'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/prueba'
    | '/'
    | '/caja'
    | '/empleados/$ID'
    | '/empleados/crear'
    | '/historial/compras'
    | '/historial/ventas'
    | '/empleados'
    | '/inventario'
    | '/empleados/editar/$ID'
    | '/inventario/paquetes/crear'
    | '/inventario/productos/crear'
    | '/inventario/proveedores/crear'
    | '/inventario/productos'
    | '/inventario/proveedores'
    | '/inventario/paquetes/editar/$ID'
    | '/inventario/productos/editar/$ID'
    | '/inventario/proveedores/editar/$ID'
  id:
    | '__root__'
    | '/_menu'
    | '/login'
    | '/prueba'
    | '/inventario/_inv'
    | '/_menu/'
    | '/caja/'
    | '/_menu/empleados/$ID'
    | '/_menu/empleados/crear'
    | '/_menu/historial/compras'
    | '/_menu/historial/ventas'
    | '/_menu/empleados/'
    | '/inventario/_inv/'
    | '/_menu/empleados/editar/$ID'
    | '/inventario/_inv/paquetes/crear'
    | '/inventario/_inv/productos/crear'
    | '/inventario/_inv/proveedores/crear'
    | '/inventario/_inv/productos/'
    | '/inventario/_inv/proveedores/'
    | '/inventario/_inv/paquetes/editar/$ID'
    | '/inventario/_inv/productos/editar/$ID'
    | '/inventario/_inv/proveedores/editar/$ID'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MenuRouteRoute: typeof MenuRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  PruebaRoute: typeof PruebaRoute
  CajaIndexRoute: typeof CajaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/prueba': {
      id: '/prueba'
      path: '/prueba'
      fullPath: '/prueba'
      preLoaderRoute: typeof PruebaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_menu': {
      id: '/_menu'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof MenuRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caja/': {
      id: '/caja/'
      path: '/caja'
      fullPath: '/caja'
      preLoaderRoute: typeof CajaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_menu/': {
      id: '/_menu/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MenuIndexRouteImport
      parentRoute: typeof MenuRouteRoute
    }
    '/inventario/_inv': {
      id: '/inventario/_inv'
      path: ''
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioInvRouteImport
      parentRoute: typeof InventarioRoute
    }
    '/inventario/_inv/': {
      id: '/inventario/_inv/'
      path: '/'
      fullPath: '/inventario/'
      preLoaderRoute: typeof InventarioInvIndexRouteImport
      parentRoute: typeof InventarioInvRoute
    }
    '/_menu/empleados/': {
      id: '/_menu/empleados/'
      path: '/empleados'
      fullPath: '/empleados'
      preLoaderRoute: typeof MenuEmpleadosIndexRouteImport
      parentRoute: typeof MenuRouteRoute
    }
    '/_menu/historial/ventas': {
      id: '/_menu/historial/ventas'
      path: '/historial/ventas'
      fullPath: '/historial/ventas'
      preLoaderRoute: typeof MenuHistorialVentasRouteImport
      parentRoute: typeof MenuRouteRoute
    }
    '/_menu/historial/compras': {
      id: '/_menu/historial/compras'
      path: '/historial/compras'
      fullPath: '/historial/compras'
      preLoaderRoute: typeof MenuHistorialComprasRouteImport
      parentRoute: typeof MenuRouteRoute
    }
    '/_menu/empleados/crear': {
      id: '/_menu/empleados/crear'
      path: '/empleados/crear'
      fullPath: '/empleados/crear'
      preLoaderRoute: typeof MenuEmpleadosCrearRouteImport
      parentRoute: typeof MenuRouteRoute
    }
    '/_menu/empleados/$ID': {
      id: '/_menu/empleados/$ID'
      path: '/empleados/$ID'
      fullPath: '/empleados/$ID'
      preLoaderRoute: typeof MenuEmpleadosIDRouteImport
      parentRoute: typeof MenuRouteRoute
    }
    '/inventario/_inv/proveedores/': {
      id: '/inventario/_inv/proveedores/'
      path: '/proveedores'
      fullPath: '/inventario/proveedores'
      preLoaderRoute: typeof InventarioInvProveedoresIndexRouteImport
      parentRoute: typeof InventarioInvRoute
    }
    '/inventario/_inv/productos/': {
      id: '/inventario/_inv/productos/'
      path: '/productos'
      fullPath: '/inventario/productos'
      preLoaderRoute: typeof InventarioInvProductosIndexRouteImport
      parentRoute: typeof InventarioInvRoute
    }
    '/inventario/_inv/proveedores/crear': {
      id: '/inventario/_inv/proveedores/crear'
      path: '/proveedores/crear'
      fullPath: '/inventario/proveedores/crear'
      preLoaderRoute: typeof InventarioInvProveedoresCrearRouteImport
      parentRoute: typeof InventarioInvRoute
    }
    '/inventario/_inv/productos/crear': {
      id: '/inventario/_inv/productos/crear'
      path: '/productos/crear'
      fullPath: '/inventario/productos/crear'
      preLoaderRoute: typeof InventarioInvProductosCrearRouteImport
      parentRoute: typeof InventarioInvRoute
    }
    '/inventario/_inv/paquetes/crear': {
      id: '/inventario/_inv/paquetes/crear'
      path: '/paquetes/crear'
      fullPath: '/inventario/paquetes/crear'
      preLoaderRoute: typeof InventarioInvPaquetesCrearRouteImport
      parentRoute: typeof InventarioInvRoute
    }
    '/_menu/empleados/editar/$ID': {
      id: '/_menu/empleados/editar/$ID'
      path: '/empleados/editar/$ID'
      fullPath: '/empleados/editar/$ID'
      preLoaderRoute: typeof MenuEmpleadosEditarIDRouteImport
      parentRoute: typeof MenuRouteRoute
    }
    '/inventario/_inv/proveedores/editar/$ID': {
      id: '/inventario/_inv/proveedores/editar/$ID'
      path: '/proveedores/editar/$ID'
      fullPath: '/inventario/proveedores/editar/$ID'
      preLoaderRoute: typeof InventarioInvProveedoresEditarIDRouteImport
      parentRoute: typeof InventarioInvRoute
    }
    '/inventario/_inv/productos/editar/$ID': {
      id: '/inventario/_inv/productos/editar/$ID'
      path: '/productos/editar/$ID'
      fullPath: '/inventario/productos/editar/$ID'
      preLoaderRoute: typeof InventarioInvProductosEditarIDRouteImport
      parentRoute: typeof InventarioInvRoute
    }
    '/inventario/_inv/paquetes/editar/$ID': {
      id: '/inventario/_inv/paquetes/editar/$ID'
      path: '/paquetes/editar/$ID'
      fullPath: '/inventario/paquetes/editar/$ID'
      preLoaderRoute: typeof InventarioInvPaquetesEditarIDRouteImport
      parentRoute: typeof InventarioInvRoute
    }
  }
}

interface MenuRouteRouteChildren {
  MenuIndexRoute: typeof MenuIndexRoute
  MenuEmpleadosIDRoute: typeof MenuEmpleadosIDRoute
  MenuEmpleadosCrearRoute: typeof MenuEmpleadosCrearRoute
  MenuHistorialComprasRoute: typeof MenuHistorialComprasRoute
  MenuHistorialVentasRoute: typeof MenuHistorialVentasRoute
  MenuEmpleadosIndexRoute: typeof MenuEmpleadosIndexRoute
  MenuEmpleadosEditarIDRoute: typeof MenuEmpleadosEditarIDRoute
}

const MenuRouteRouteChildren: MenuRouteRouteChildren = {
  MenuIndexRoute: MenuIndexRoute,
  MenuEmpleadosIDRoute: MenuEmpleadosIDRoute,
  MenuEmpleadosCrearRoute: MenuEmpleadosCrearRoute,
  MenuHistorialComprasRoute: MenuHistorialComprasRoute,
  MenuHistorialVentasRoute: MenuHistorialVentasRoute,
  MenuEmpleadosIndexRoute: MenuEmpleadosIndexRoute,
  MenuEmpleadosEditarIDRoute: MenuEmpleadosEditarIDRoute,
}

const MenuRouteRouteWithChildren = MenuRouteRoute._addFileChildren(
  MenuRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MenuRouteRoute: MenuRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  PruebaRoute: PruebaRoute,
  CajaIndexRoute: CajaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
